dangdang/urls.py
from django.urls import path

from dangdang import views

app_name='dangdang'
urlpatterns = [
    path('index/', views.index,name='index'),
    path('lok_booklist/', views.booklist,name='booklist'),
    path('login/', views.login,name='login'),
    path('regist/', views.regist,name='regist'),
    path('registlogic/', views.regist_logic,name='registlogic'),
    path('registOk/', views.regist_ok,name='registOk'),
    path('login_logic/', views.login_logic,name='loginlogic'),
    path('getcaptcha/', views.getcaptcha,name='getcaptcha'),
    path('ajaxCode/', views.ajax_code,name='ajaxCode'),
    path('ajaxName/', views.ajax_name,name='ajaxName'),
    path('ajaxOut/', views.ajaxOut,name='ajaxOut'),
    # path('ajaxEmail/', views.ajaxEmail,name='ajaxEmail'),
]

operapp/urls.py
from django.urls import path

from operapp import views
app_name='operapp'
urlpatterns = [
    path('cart/',views.cart,name='cart'),
    path('bookIntro/',views.book_intro,name='bookIntro'),
    path('addCart/',views.add_cart,name='addCart'),
    path('updateCart/',views.update_cart,name='updateCart'),
    path('delBook/',views.del_book,name='delBook'),
    path('cartSubmit/',views.cartSubmit,name='cartSubmit'),
    path('submitOK/',views.submitOK,name='submitOK'),
    path('cartSubmitOK/',views.cartSubmitOK,name='cartSubmitOK'),
    path('Ajaxaddress/',views.Ajaxaddress,name='Ajaxaddress'),
    path('Orderdetail/',views.Orderdetail,name='Orderdetail'),
    path('AjaxSaveCart/',views.AjaxSaveCart,name='AjaxSaveCart'),
]

untitled/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dangdang/', include('dangdang.urls')),
    path('operapp/', include('operapp.urls')),
]

templates/Orderdetail.html
<!DOCTYPE html>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
{% load static %}
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>购物车</title>
<script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/jquery.1.4.2-min.js' %}"></script>
	<link rel="shortcut icon" href="{% static 'images/favicon.ico?v=20160901' %}" type="image/x-icon">
    <link href="{% static 'css/shopping_cart_new.css' %}" rel="stylesheet" type="text/css">
	<link href="{% static 'css/footer_150526.css' %}" rel="stylesheet" type="text/css" /


</head>

<body style="padding-bottom:82px">

<link href="{% static 'css/header_960_150611.css' %}" rel="stylesheet" type="text/css">
<script src="{% static 'js/pagetop2015_0827.js' %}" charset="utf-8" type="text/javascript"></script>

<div id="hd">
<div id="tools">
<div class="tools">
    <div class="ddnewhead_operate" dd_name="顶链接">
        
        <div class="ddnewhead_welcome" >
            <span id="nickname" style="color: red ">
                <span class="hi hi_none">欢迎光临当当，请</span>
                <a href="{% url 'dangdang:login' %}?login_flag=cart" class="login_link">登录</a>
                <a href="{% url 'dangdang:regist' %}?regist_flag=cart" >免费注册</a></span>
        </div>

    </div>
</div>
</div>
<div id="header_end"></div>
<!--CreateDate  2016-09-28 11:30:01--></div>
<form action="http://search.dangdang.com/search.aspx" id="bootpagetopSearch" name="bootpagetopSearch" method="GET"></form>
<script type="text/javascript">var nick_num = 0;initHeaderOperate();</script><script type="text/javascript" src="http://orderb.dangdang.com/queryunpaid?callback=Unpaid_Data"></script>
		<div class="shoppingcart_wrapper" id="ad_cpt_11850"><div><a href="{% url 'dangdang:index' %}" target="_blank" rel="nofollow">
            <img src="http://img62.ddimg.cn/2017/1/11/2017011111344969879.jpg"></a></div></div>
<div class="logo_line">
    <div class="w960">
        <br>
        <hr>
        <div align="center"><span style="font-size: 40px; color: red ;">订单详情</span></div>
    </div>
</div>
<div class="add_line" id="district">
    <div class="w960">
    </div>
</div>





{#购物车商品区#}
{#<div id="cart_main">#}
{#    {% if cart.cart_items %}#}
{#    <div class="w960" id="cart">#}
{#    <ul class="shopping_title" id="j_carttitle">#}
{#        <li class="f1">#}
{#            <button class="checknow fn-checkall" type="button" id="j_selectall" style="background: none;border: none;">全选</button></li>#}
{#        <li class="f2">商品信息</li>#}
{#        <li class="f3">市场价价（元）</li>#}
{#        <li class="f3">当当价（元）</li>#}
{#        <li class="f4">数量</li>#}
{#        <li class="f4">金额（元）</li>#}
{#        <li class="f5">操作</li>#}
{#    </ul>#}
{##}
{##}
{##}
{#    商品详情#}
{#    <div class="cart_main">#}
{#       <div class="fn-shops" id="J_cartContent" >#}
{#        <div class="fn-shop">#}
{#            <table border="0" cellspacing="0" cellpadding="0" class="shop_title" style="padding-left:0px;">#}
{#                <tbody>#}
{#                <tr>#}
{#                    <td><a href="javascript:void(0)" dd_name="选中店铺" class="checknow fn-shop-checkall check_on">选中</a></td>#}
{#                    <td><span class="shop_icon"></span></td> <td><a href="http://www.dangdang.com" target="_blank">当当自营</a></td>#}
{#                </tbody>#}
{#            </table>#}
{##}
{#            <div class="shopping_list" >#}
{#            <table width="100%" border="0" cellspacing="0" cellpadding="0">#}
{##}
{##}
{##}
{##}
{#                遍历购物车商品#}
{#                {% for i in  cart.cart_items %}#}
{#                    <tbody data-stock="22388" data-offline="false" data-productid="24147882" data-timestamp="1484488454000" data-orderforspupormo="0">#}
{#                        <tr id="tr_424893864" class="  ">#}
{#                            <td class="row1">#}
{#                                <input type="checkbox" class="cart_checkbox" style="width:15px; height:15px;" id="checked{{ forloop.counter0 }}" onclick="count('{{ i.book.book_id }}')">#}
{#                                <span style="display:none; ">{{ i.book.book_id }}</span>#}
{#                            </td>#}
{#                            <td class="row_img">#}
{#                                <a href="http://product.dangdang.com/24147882.html" target="_blank" dd_name="查看详情">#}
{#                                <img onmouseout="$(this).parent().next().hide()" onmouseover="$(this).parent().next().show()" src="http://img3x2.ddimg.cn/0/17/24147882-1_m.jpg" width="80" height="80">#}
{#                                </a>#}
{#                                <div style="display: none;" class="img_big">#}
{#                                    <a href="http://product.dangdang.com/24147882.html" dd_name="查看详情" target="_blank">#}
{#                                    <img src="http://img3x2.ddimg.cn/0/17/24147882-1_b.jpg">#}
{#                                    </a>#}
{#                                    <span class="arrow"></span>#}
{#                                </div>#}
{#                            </td>#}
{#                            <td class="row_name" style="width:160px;">#}
{#                                <div class="name">#}
{#                                    <a href="{% url 'operapp:bookIntro' %}?bookid={{ i.book.book_id }}" title="{{ i.book.book_name }}" target="_blank" dd_name="查看详情" style="word-break:break-all;  word-wrap:break-word;">{{ i.book.book_name }}</a>#}
{#                                </div>#}
{#                            </td>#}
{#                            <td class="row3">#}
{#                                <span id="price{{ i.book.book_id }}" >{{ i.book.book_price }}</span>#}
{#                            </td>#}
{#                            <td class="row3">#}
{#                                <span id="dprice{{ i.book.book_id }}" >{{ i.book.book_dprice }}</span>#}
{#                            </td>#}
{#                            <td data-minbuy="0" class="fn-count-tip row3">#}
{#                                <span class="amount fn-updatecount " data-value="1">#}
{#                                    <a dd_name="减少数量" href="javascript:void(0)" onclick="updateJQ(('-'),'{{ i.book.book_id }}')">-</a>#}
{#                                    <input data-value="1" value="{{ i.amount }}" type="text" id="num{{ i.book.book_id }}" onblur="updateJQ((''),'{{ i.book.book_id }}')">#}
{#                                    <a dd_name="增加数量" href="javascript:void(0)" onclick="updateJQ(('+'),'{{ i.book.book_id }}')">+</a>#}
{#                                </span>#}
{#                            </td>#}
{#                            <td class="row4">#}
{#                                <span class="red sums" id="total{{ i.book.book_id }}" >{% widthratio i.book.book_dprice 1 i.amount %}</span>#}
{#                            </td>#}
{#                            <td class="row5 ">#}
{#                                <span><a href="javascript:void(0)" data-item="424893864" class="fn-add-wish" dd_name="加入收藏按钮">移入收藏</a></span>#}
{#                                <span>#}
{#                                    <a href="#" onclick="delbook('{{ i.book.book_id }}')" data-item="424893864" class="fn-remove-product" dd_name="删除普通品">删除</a>#}
{#                                </span>#}
{#                            </td>#}
{#                        </tr>#}
{#                    </tbody>#}
{#                {% endfor %}#}
{##}
{##}
{##}
{##}
{#                <tfoot>#}
{#                    <tr class="total">#}
{#                        <td class="row1">&nbsp;#}
{#                        </td> <td class="row_img">店铺合计</td>#}
{#                        <td colspan="2">&nbsp;</td>#}
{#                        <td colspan="3" class="row4">#}
{#                            <span class="red big ooline alignright cart_total" id="total01">¥0</span>#}
{#                        </td>#}
{#                    </tr>#}
{#                </tfoot>#}
{#            </table>#}
{#        </div>#}
{##}
{##}
{##}
{##}
{##}
{#</div>#}
{##}
{#    <div id="hide_div" style="height:0px;visibility:hidden;"></div>#}
{#    <div style="position:static;bottom:-20px;z-index: 101;width:100%;left:0px;">#}
{#    <div class="shopping_total" id="J_totalMoneyBlock">#}
{##}
{#    <div class="shopping_total_right">#}
{#    <a class="total_btn fn-checkout" href="#" onclick="cartSumbit()" id="checkout_btn" dd_name="结算">结&nbsp;&nbsp;算</a>#}
{#    <div class="subtotal">#}
{#    <p><span class="cartsum">总计(不含运费)：</span><span id="total02" class="price cart_total">¥0</span></p>#}
{#    <p><span class="cartsum">已节省：</span><span id="save" >¥0</span></p>#}
{#    </div>#}
{#    </div>#}
{#    </div>#}
{#    </div>#}
{##}
{#</div>#}
{#    </div>#}
{##}
{#</div>#}
{#    {% else%}#}
{#        <div align="center"><span  style="font-size:45px; color:green;">购物车里还没有商品，去   <a href="{% url 'dangdang:index' %}" style="color: red ;" >【主页】</a>选购商品吧，GO</span></div>#}
{#    {% endif %}#}
{#</div>#}




<div id="footer" >
<div class="footer">
	<div class="footer_nav_box">
		<div class="footer_copyright"><span>Copyright (C) 当当网 2004-2014, All Rights Reserved</span><a href="http://www.hd315.gov.cn/beian/view.asp?bianhao=010202001051000098" target="_blank" class="footer_img" rel="nofollow"><img src="http://img4.dangdang.com/bottom/validate.gif"></a><span><a href="http://www.miibeian.gov.cn/" target="_blank" rel="nofollow">京ICP证041189号</a></span><span>出版物经营许可证&nbsp;新出发京批字第直0673号</span></div>
	</div>
</div>
</div>


</body>
<script>
    {% if nickname %}
        console.log(nickname);
        document.getElementById('nickname').innerHTML='<span class="hi">Hi，\n'+
        '        <a href="http://myhome.dangdang.com/" class="login_link" target="_blank">\n'+
        '        <b>{{ nickname }}</b></a>\n'+
        '        <a href="{% url "dangdang:index" %}" onclick="outFn()" class="login_link">登出</a></span>\n'+
        '        {% endif %}'
</script>
</html>

templates/indent ok.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
{% load static %}
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>无标题文档</title>
<script src="{% static 'js/jquery_1.8.js' %}"></script>
    <script src="{% static 'js/jquery_cookie.js' %}"></script>
	<link rel="shortcut icon" href="images/favicon.ico?v=20160901" type="image/x-icon">
    <link href="{% static 'css/shopping_cart_new.css' %}" rel="stylesheet" type="text/css">
	<link href="{% static 'css/footer_150526.css' %}" rel="stylesheet" type="text/css" />
    <script>
        {#登出函数#}
        function outFn() {
            var xhr;
            if (window.ActiveXObject){
                xhr = new ActiveXObject()
            } else if (window.XMLHttpRequest){
                xhr=new XMLHttpRequest()
            }
            url="{% url 'dangdang:ajaxOut' %}";
            xhr.open('get', url, true);
            xhr.send();
            xhr.onreadystatechange=function(){
            if (xhr.readyState ===4 && xhr.status ===200){
                alert('登出成功！')
            }
            }
        }
    </script>
</head>

<body style="padding-bottom:82px">

<link href="{% static 'css/header_960_150611.css' %}" rel="stylesheet" type="text/css">
<script src="{% static 'js/pagetop2015_0827.js' %}" charset="gb2312" type="text/javascript"></script>

<div id="hd">
<div id="tools">
<div class="tools">
    <div class="ddnewhead_operate" dd_name="顶链接">
        <div class="ddnewhead_welcome" >
            {% if nickname %}
            <span class="hi">Hi，
                <a href="http://myhome.dangdang.com/" class="login_link" target="_blank">
                    <b>{{ nickname }}</b>
                </a>
                <a href="{% url "dangdang:index" %}" onclick="outFn()" class="login_link">登出</a>
            </span>
            {% else %}
                <span id="nickname" style="color: red ">
                <span class="hi hi_none">欢迎光临当当，请</span>
                <a href="{% url 'dangdang:login' %}?login_flag=cart" class="login_link">登录</a>
                <a href="{% url 'dangdang:regist' %}?regist_flag=cart" >免费注册</a></span>
            {% endif %}
        </div>
    </div>
</div>
</div>
<div id="header_end"></div>
</div>
<form action="http://search.dangdang.com/search.aspx" id="bootpagetopSearch" name="bootpagetopSearch" method="GET"></form>
<script type="text/javascript">var nick_num = 0;initHeaderOperate();</script><script type="text/javascript" src="http://orderb.dangdang.com/queryunpaid?callback=Unpaid_Data"></script>
		<div class="shoppingcart_wrapper" id="ad_cpt_11850"><div><a href="http://a.dangdang.com/tjump.php?q=ddo84XQOf357bOs8tXGg5%2F%2F0oVoDImt3DFWsMqu7ZMSVsfUMeOQJueASNiMLjq%2FdrXMLCKnVfyKEahteAh1ih%2ByKYrKGzhvL20LVbDzObRambBA0YPpivy5hR5foQ4Rt%2BTB" target="_blank" rel="nofollow"><img src="http://img62.ddimg.cn/2017/1/11/2017011111344969879.jpg"></a></div></div>
<div class="logo_line">
    <div class="w960">
        <div class="shopping_procedure02 shopping_procedure "><span>我的购物车</span><span>填写订单</span><span class="current">完成订单</span></div>
        <div class="logo"><a href="#"><img src="{% static 'images/bz_logo_car.jpg' %}" alt=""></a></div>
    </div>
</div>
<div class="checkout-wrap"><div class="indent_con">
	<div class="order-box orderEnd-box">
            <div class="orderEnd-box-top">
                <div class="topbar">
                </div>
                <h2 align="center">
                    <span id="spanOrderTip" class="text" style="padding-right:240px; ">感谢您提交订单，我们将及时为您处理！</span>
                    <br>
                    <span><a href="{% url 'dangdang:index' %}">【返回首页】</a></span>
                </h2>
            </div>



            <div class="orderEnd-box-cont">
                <div id="NotPeerPayOrderList" class="pay-instead-order"></div>
                <div class="pay-normal" id="order_list">
                    <div class="item-order">
                        <h3>订单：
                            <a href="http://order.dangdang.com/orderdetails.aspx?orderid=34673930343" target="_blank">
                                <span class="number">{{ torderobj.id }}</span>
                            </a>
                        </h3>
                        <div class="cont minh-40">
                            <table cellpadding="0" cellspacing="0">
                                <tbody>
                                    <tr>
                                    <td width="53"></td>
                                    <td>
                                        <span class="popup-Details spd">{{ countsums }}件商品
                                            <i class="icon icon-details"></i>
                                        </span>

                                        <span>送给</span>
                                        <span class="popup-Details spd">{{ torderobj.order_addrid.name }}<i class="icon icon-details"></i>
                                        </span>
                                        <span>配送方为</span>
                                        <span>当当网</span>
                                    </td>
                                    </tr>
                                    <tr class="hackie6"><td>&nbsp;</td></tr>
                                </tbody></table></div>
                        <div class="order-price"><p>支付金额：<span class="price-d">¥{{ torderobj.price }}</span>        </p><p class="p-hdfk">货到付款</p></div>					<div class="itemtext"><span class="color-red">安全提醒：</span>当当平台及销售商不会以订单异常、系统升级等理由，通过任何方式发送给您退款链接。请您谨防<span class="color-red">钓鱼链接或诈骗电话</span>！</div></div></div>




                <div class="item-order item-order-payment" id="error_prompt" style="display:none;"> <!-- 需要隐藏，添加hide类即可 -->
                    <div class="tips-pay">
                        <strong>温馨提示：</strong>
                        <span>如果您有网上支付、银行转账的订单，请您在<strong class="color-red">24</strong>小时内支付 <a href="http://order.dangdang.com/myallorders" id="a_myorder">查看订单</a> </span><br>
                        <span style="padding-left:67px;">您还有 <strong class="color-red">1</strong> 张"待提交"订单 <a href="http://shopping.dangdang.com/shoppingcart/dispart_order.aspx" id="a_submitorder">继续提交</a></span>
                    </div>
                </div>
            </div>


    </div>
</div>
</div>

<div id="footer">
<div class="footer">
	<div class="footer_nav_box">
		<div class="footer_copyright"><span>Copyright (C) 当当网 2004-2014, All Rights Reserved</span><a href="http://www.hd315.gov.cn/beian/view.asp?bianhao=010202001051000098" target="_blank" class="footer_img" rel="nofollow"><img src="http://img4.dangdang.com/bottom/validate.gif"></a><span><a href="http://www.miibeian.gov.cn/" target="_blank" rel="nofollow">京ICP证041189号</a></span><span>出版物经营许可证&nbsp;新出发京批字第直0673号</span></div>
	</div>
</div>
</div>
    <div class="foot_tip_ad">广告</div>
    <style>
        .foot_tip_ad { width:40px; height:40px; font:12px/40px "simsun"; text-align:center; color:#fff; background-color:#474747; position:fixed; right:0; bottom:10px;_position:absolute; _bottom:auto;_top:expression(eval(document.documentElement.scrollTop+document.documentElement.clientHeight-this.offsetHeight-(parseInt(this.currentStyle.marginTop,10)||0)-(parseInt(this.currentStyle.marginBottom,10)||0)));}
    </style>


</body>
</html>

templates/indent.html
<!DOCTYPE html>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
{% load static %}
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>无标题文档</title>
<script src="{% static 'js/jquery1.4.2.js  ' %}"></script>
    <script src="{% static 'js/jquery.1.4.2-min.js ' %}"></script>
	<link rel="shortcut icon" href="images/favicon.ico?v=20160901" type="image/x-icon">
    <link href="{% static 'css/shopping_cart_new.css' %}" rel="stylesheet" type="text/css">
	<link href="{% static 'css/footer_150526.css' %}" rel="stylesheet" type="text/css" />
</head>

<body style="padding-bottom:82px">

<link href="{% static 'css/header_960_150611.css' %}" rel="stylesheet" type="text/css">
<script src="{% static 'js/pagetop2015_0827.js' %}" charset="gb2312" type="text/javascript"></script>

<script>
        var dawk_flag1=false,phone_flag2=false;
        {#登出函数#}
        function outFn() {
            var xhr;
            if (window.ActiveXObject){
                xhr = new ActiveXObject()
            } else if (window.XMLHttpRequest){
                xhr=new XMLHttpRequest()
            }
            url="{% url 'dangdang:ajaxOut' %}";
            xhr.open('get', url, true);
            xhr.send();
            xhr.onreadystatechange=function(){
            if (xhr.readyState ===4 && xhr.status ===200){
                alert('登出成功！')
            }
            }
        }


        function Address() {

            var addID = $('#address').val();

            {% for i in addressList  %}
                if (addID == "{{ i.id }}") {
                    $('#address_message').html(
                        '<li><label><strong>*</strong>收&nbsp;&nbsp;货&nbsp;&nbsp;人：</label><input class="input" type="text" name="name" disabled="disabled" value="{{ i.name }}"></li>' +
                        '<li><label><strong>*</strong>收货地区：</label><input class="input" type="text" name="region" disabled="disabled " value="{{ i.region }}" ></li>' +
                        '<li><label><strong>*</strong>详细地址：</label><input class="input" type="text" name="site" disabled="disabled " value="{{ i.site }}"></li>' +
                        '<li><label><strong>*</strong>邮政编码：</label><input class="input" type="text" name="postal_code" disabled="disabled " value="{{ i.postal_code }}" ></li>' +
                        '<li><label><strong>*</strong>手&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;机：</label><input class="input" type="text" name="number" disabled="disabled " value="{{ i.number }}"></li>' +
                        '<input type="hidden" name="addressFlag" value="1">');
                }else if(addID=="new"){
                    $('.input').removeAttr('value');
                    $('.input').removeAttr('disabled');
                }
            {% endfor %}
        }
        function sub() {
            var dawk= /^[1-9][0-9]{5}$/;
            var phone = /^1([38][0-9]|4[579]|5[0-3,5-9]|6[6]|7[0135678]|9[89])\d{8}$/;

            if  (!dawk.test($('#dawk').val())){
                alert("邮编填写错误，请重新填写！");
                    return 0;}
                else if($('#phone').val() != ""){
                    if (!phone.test($('#phone').val())){
                        alert("手机号填写有误，请重新填写！");
                        return 0;}
        }}


        {#提交订单函数#}
        function submitFn(){

            inp=document.getElementsByTagName('input');
            inp1=$('input');
            var i=1;

            for(;i<6;i++){
                if (! inp1[i].value) {
                    alert('填写信息不能为空，请确认后在提交！');
                    break;
                }
            }
            if (i==6){
                $('.input').removeAttr('disabled');
                        console.log(11)
                        document.forms[0].submit()
            }
        }




</script>



<div id="hd">
<div id="tools">
<div class="tools">
    <div class="ddnewhead_operate" dd_name="顶链接">
        <div class="ddnewhead_welcome" >
            {% if nickname %}
            <span class="hi">Hi，
                <a href="http://myhome.dangdang.com/" class="login_link" target="_blank">
                    <b>{{ nickname }}</b>
                </a>
                <a href="{% url "dangdang:index" %}" onclick="outFn()" class="login_link">登出</a>
            </span>
            {% else %}
                <span id="nickname" style="color: red ">
                <span class="hi hi_none">欢迎光临当当，请</span>
                <a href="{% url 'dangdang:login' %}?login_flag=cart" class="login_link">登录</a>
                <a href="{% url 'dangdang:regist' %}?regist_flag=cart" >免费注册</a></span>
            {% endif %}
        </div>
    </div>
</div>
</div>
<div id="header_end">

</div>
<!--CreateDate  2016-09-28 11:30:01-->
</div>
<script type="text/javascript">var nick_num = 0;initHeaderOperate();</script>
<script type="text/javascript" src="http://orderb.dangdang.com/queryunpaid?callback=Unpaid_Data"></script>

<div class="shoppingcart_wrapper" id="ad_cpt_11850"><div>
    <a href="http://a.dangdang.com/tjump.php?q=ddo84XQOf357bOs8tXGg5%2F%2F0oVoDImt3DFWsMqu7ZMSVsfUMeOQJueASNiMLjq%2FdrXMLCKnVfyKEahteAh1ih%2ByKYrKGzhvL20LVbDzObRambBA0YPpivy5hR5foQ4Rt%2BTB" target="_blank" rel="nofollow"><img src="http://img62.ddimg.cn/2017/1/11/2017011111344969879.jpg"></a></div></div>
<div class="logo_line">
    <div class="w960">
        <div class="shopping_procedure01 shopping_procedure ">
            <span>我的购物车</span>
            <span class="current">填写订单</span><span>完成订单</span>
        </div>
        <div class="logo">
            <a href="#"><img src="{% static 'images/bz_logo_car.jpg' %}" alt=""></a>
        </div>
    </div>
</div>
<div class="indent_con">
	<div class="shdz" align="center" >
    	<h3>收货相关信息</h3>
        <br><br>
             <p style="font-size: 15px;color: #0d0d0d ">▪ 收货地址
                <span style="padding-left: 30px;">
                    选择地址信息:
                    <select name="site" id="address" onchange="Address()">
                        <option value="new">填写新地址</option>
                    {% for i in addressList %}
                        <option value="{{ i.id }}">{{ i.name }}</option>
                    {% endfor %}
                    </select>
                </span>
            </p>


{#        表单提交收货人信息#}
        <form action="{% url 'operapp:submitOK' %}" method="post">
            {% csrf_token %}
            <ul class="shdz_con" id="address_message" style="width:300px;">
        	<li><label><strong>*</strong>收&nbsp;&nbsp;货&nbsp;&nbsp;人：</label><input type="text"  name="name" ></li>
        	<li><label><strong>*</strong>收货地区：</label><input type="text" name="region"  ></li>
            <li><label><strong>*</strong>详细地址：</label><input type="text" name="site" ></li>
            <li><label><strong>*</strong>邮政编码：</label><input type="text" name="postal_code" id="dawk" onclick="sub()"></li>
            <li><label><strong>*</strong>手&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;机：</label><input type="text" name="number" id="phone" onclick="sub()"></li>
                <input type="hidden" name="addressFlag" value="0">
            </ul>


        <div class="balance"><p>商品金额：¥{{ total }}</p><p class="yfze">应付总额（含运费）：
            <em>¥{{ total }}</em></p><p>
            <input type="hidden" name="total" value="{{ total }}">
            <a href="#" onclick="submitFn()">提交订单</a></p></div>
        </form>
    </div>
</div>







<div id="footer">
<div class="footer">
	<div class="footer_nav_box">
		<div class="footer_copyright"><span>Copyright (C) 当当网 2004-2014, All Rights Reserved</span><a href="http://www.hd315.gov.cn/beian/view.asp?bianhao=010202001051000098" target="_blank" class="footer_img" rel="nofollow"><img src="http://img4.dangdang.com/bottom/validate.gif"></a><span><a href="http://www.miibeian.gov.cn/" target="_blank" rel="nofollow">京ICP证041189号</a></span><span>出版物经营许可证&nbsp;新出发京批字第直0673号</span></div>
	</div>
</div>
</div>
    <div class="foot_tip_ad">广告</div>
    <style>
        .foot_tip_ad { width:40px; height:40px; font:12px/40px "simsun"; text-align:center; color:#fff; background-color:#474747; position:fixed; right:0; bottom:10px;_position:absolute; _bottom:auto;_top:expression(eval(document.documentElement.scrollTop+document.documentElement.clientHeight-this.offsetHeight-(parseInt(this.currentStyle.marginTop,10)||0)-(parseInt(this.currentStyle.marginBottom,10)||0)));}
    </style>


</body>
</html>